In [1]:
from datasets import load_dataset

ds = load_dataset("UtkarshM005/grafite-jee-mains-qna-no-img")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/742 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00000-of-00001.parquet:   0%|          | 0.00/5.79M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/11392 [00:00<?, ? examples/s]

In [2]:
df = ds["train"].to_pandas()

In [3]:
df = ds["train"].to_pandas()
df.to_csv("jee_data_all.csv", index=False)

In [4]:
import pandas as pd
df_new = pd.read_csv('/content/jee_data_all.csv')

In [5]:
df['subject'].unique()

array(['chemistry', 'maths', 'physics'], dtype=object)

In [6]:
df_math = df[df['subject'] == 'maths']

In [7]:
df_math.head()

,question_id,subject,chapter,topic,question,options,correct_option,answer,explanation,question_type,paper_id,solution,__index_level_0__
3372,kt4Qsk8Vq7TCfuAU,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,"The two lines $$x=ay+b,z=cy+d$$ and $$x = a'y ...","[{""identifier"": ""A"", ""content"": ""$$aa' + cc' +...","[""A""]",None,$${{x - b} \over a} = {y \over 1} = {{z - d} \...,mcq,aieee-2003,$$aa' + cc' + 1 = 0$$,3373
3373,UTyglZ3FzG2VUgaZ,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,"A line makes the same angle $$\theta $$, with ...","[{""identifier"": ""A"", ""content"": ""$${2 \\over 5...","[""C""]",None,<b>Concept :</b> If a line makes the angle $$\...,mcq,aieee-2004,$${3 \over 5}$$,3374
3374,YwetrlhmGeDvUihA,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,If a line makes an angle of $$\pi /4$$ with th...,"[{""identifier"": ""A"", ""content"": ""$${\\pi \\ov...","[""B""]",None,Let the angle of line makes with the positive ...,mcq,aieee-2007,$${\pi \over 2}$$,3375
3375,6XCk3G13gwVOzXa9,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,Let $$L$$ be the line of intersection of the p...,"[{""identifier"": ""A"", ""content"": ""$$1$$ ""}, {""i...","[""C""]",None,Let the direction cosines of line $$L$$ be $$l...,mcq,aieee-2007,$${1 \over {\sqrt 3 }}$$,3376
3376,liW5CBWFat8KJOch,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,The projections of a vector on the three coord...,"[{""identifier"": ""A"", ""content"": ""$${6 \\over 5...","[""B""]",None,"Let $$P\left( {{x_1},{y_1},{z_1}} \right)$$ an...",mcq,aieee-2009,"$${6 \over 7 },{{ - 3} \over 7},{2 \over 7}$$",3377

In [8]:
df_math = df_math.reset_index(drop = 'True')

In [9]:
df_math

,question_id,subject,chapter,topic,question,options,correct_option,answer,explanation,question_type,paper_id,solution,__index_level_0__
0,kt4Qsk8Vq7TCfuAU,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,"The two lines $$x=ay+b,z=cy+d$$ and $$x = a'y ...","[{""identifier"": ""A"", ""content"": ""$$aa' + cc' +...","[""A""]",None,$${{x - b} \over a} = {y \over 1} = {{z - d} \...,mcq,aieee-2003,$$aa' + cc' + 1 = 0$$,3373
1,UTyglZ3FzG2VUgaZ,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,"A line makes the same angle $$\theta $$, with ...","[{""identifier"": ""A"", ""content"": ""$${2 \\over 5...","[""C""]",None,<b>Concept :</b> If a line makes the angle $$\...,mcq,aieee-2004,$${3 \over 5}$$,3374
2,YwetrlhmGeDvUihA,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,If a line makes an angle of $$\pi /4$$ with th...,"[{""identifier"": ""A"", ""content"": ""$${\\pi \\ov...","[""B""]",None,Let the angle of line makes with the positive ...,mcq,aieee-2007,$${\pi \over 2}$$,3375
3,6XCk3G13gwVOzXa9,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,Let $$L$$ be the line of intersection of the p...,"[{""identifier"": ""A"", ""content"": ""$$1$$ ""}, {""i...","[""C""]",None,Let the direction cosines of line $$L$$ be $$l...,mcq,aieee-2007,$${1 \over {\sqrt 3 }}$$,3376
4,liW5CBWFat8KJOch,maths,3d-geometry,direction-cosines-and-direction-ratios-of-a-line,The projections of a vector on the three coord...,"[{""identifier"": ""A"", ""content"": ""$${6 \\over 5...","[""B""]",None,"Let $$P\left( {{x_1},{y_1},{z_1}} \right)$$ an...",mcq,aieee-2009,"$${6 \over 7 },{{ - 3} \over 7},{2 \over 7}$$",3377
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4493,lv9s2007,maths,vector-algebra,vector-or-cross-product-of-two-vectors-and-its...,"<p>Let $$\vec{a}=2 \hat{i}+5 \hat{j}-\hat{k}, ...","[{""identifier"": ""A"", ""content"": ""15""}, {""ident...","[""C""]",None,<p>$$\begin{gathered}\n(\vec{c}+\hat{i}) \time...,mcq,jee-main-2024-online-5th-april-evening-shift,5,7867
4494,lv9s20g2,maths,vector-algebra,vector-or-cross-product-of-two-vectors-and-its...,"<p>Consider three vectors $$\vec{a}, \vec{b}, ...","[{""identifier"": ""A"", ""content"": ""124""}, {""iden...","[""A""]",None,<p>$$\begin{aligned}\n& \vec{a}=\vec{b} \times...,mcq,jee-main-2024-online-5th-april-evening-shift,124,7868
4495,lvb294hw,maths,vector-algebra,vector-or-cross-product-of-two-vectors-and-its...,"<p>Let $$\vec{a}=2 \hat{i}+\hat{j}-\hat{k}, \v...","[{""identifier"": ""A"", ""content"": ""$$\\frac{1}{3...","[""C""]",None,<p>$$\begin{aligned}\n& \vec{a}=2 \hat{i}+\hat...,mcq,jee-main-2024-online-6th-april-evening-shift,2,7869
4496,lvb294j7,maths,vector-algebra,vector-or-cross-product-of-two-vectors-and-its...,<p>Let $$\overrightarrow{\mathrm{a}}=6 \hat{i}...,"[{""identifier"": ""A"", ""content"": ""$$\\frac{3}{2...","[""C""]",None,<p>$$\begin{aligned}\n& |(\vec{a} \times \vec{...,mcq,jee-main-2024-online-6th-april-evening-shift,$$\frac{9}{2}(6+\sqrt{6})$$\n,7870
4497,lvc57b8v,maths,vector-algebra,vector-or-cross-product-of-two-vectors-and-its...,<p>Let $$\vec{a}=2 \hat{i}-3 \hat{j}+4 \hat{k}...,[],None,46,<p>Let $$\hat{i}+8 \hat{j}+13 \hat{k}=\vec{u}$...,integer,jee-main-2024-online-6th-april-morning-shift,46,7871

In [10]:
import json
import pandas as pd

# 1. Build the prompt
def build_prompt(row):
    question_text = str(row['question'])
    options_data = str(row['options'])

    prompt = question_text + "\n\nOptions:\n"
    try:
        opts = json.loads(options_data)
        for opt in opts:
            prompt += f"{opt['identifier']}) {opt['content']}\n"
    except Exception:
        prompt += options_data

    return prompt

print("Formatting prompts...")
df_math['prompt'] = df_math.apply(build_prompt, axis=1)

# 2. THE FIX: Drop the existing 'answer' column before renaming 'solution'
if 'answer' in df_math.columns and 'solution' in df_math.columns:
    df_math = df_math.drop(columns=['answer'])

df_math = df_math.rename(columns={'solution': 'answer'})

# 3. Clean up and isolate columns
df_math = df_math.dropna(subset=['prompt', 'answer', 'chapter'])
rl_df = df_math[['prompt', 'answer', 'chapter', 'topic']].copy()

# 4. Stratified Sampling (Warning Fixed)
print("Sampling 150 balanced questions...")
num_chapters = rl_df['chapter'].nunique()
samples_per_chapter = max(1, 200 // num_chapters)

# Added include_groups=False to silence the DeprecationWarning
train_df = rl_df.groupby('chapter', group_keys=False).apply(
    lambda x: x.sample(min(len(x), samples_per_chapter), random_state=42),
    include_groups=False
)

# Force exactly 200
if len(train_df) > 200:
    train_df = train_df.sample(200, random_state=42)
elif len(train_df) < 200:
    needed = 200 - len(train_df)
    filler = rl_df.drop(train_df.index, errors='ignore').sample(needed, random_state=42)
    train_df = pd.concat([train_df, filler])

# Ensure only the required columns are exported
train_df = train_df[['prompt', 'answer', 'chapter', 'topic']]

print(f"Final Train Set Size: {len(train_df)} questions.")

# 5. Export
train_df.to_json("train_rl_colab.jsonl", orient="records", lines=True)
print("Success! File train_rl_colab.jsonl is ready.")

Formatting prompts...
Sampling 150 balanced questions...
Final Train Set Size: 200 questions.
Success! File train_rl_colab.jsonl is ready.

In [1]:
# Install Unsloth and standard RL/PEFT libraries
!pip install "unsloth[colab] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps trl peft accelerate bitsandbytes xformers triton datasets

Collecting unsloth@ git+https://github.com/unslothai/unsloth.git (from unsloth[colab]@ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-9mcu86om/unsloth_cd80f368d0254f5a82d245be4d4f7148
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-9mcu86om/unsloth_cd80f368d0254f5a82d245be4d4f7148
  Resolved https://github.com/unslothai/unsloth.git to commit a6fe743ebe8055142eedba8cbbf9f62fc676a571
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.24.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.4.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.49.2)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (26.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.19.2)
Requirement already satisfied: unsloth_zoo>=2026.3.5 in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2026.3.5)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.25.0+cu128)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (3.25.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.4.3)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.0.11)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.3.0,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (5.3.0)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (4.3.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.46.3)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.13.0)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.24.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.18.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.7.1)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.1.9)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (11.3.0)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.20.0)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.37.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (5.3.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth_zoo>=2026.3.5->unsloth@ git+https://github.com/unslothai/unsloth.git->unsloth[colab]@ git+https://github.com/unslothai/unsloth.git) (1.4.2)

In [2]:
!unzip phi-4-jee-math-lora.zip -d phi-4-jee-math-lora

Archive:  phi-4-jee-math-lora.zip
  inflating: phi-4-jee-math-lora/adapter_config.json
  inflating: phi-4-jee-math-lora/chat_template.jinja
  inflating: phi-4-jee-math-lora/adapter_model.safetensors
  inflating: phi-4-jee-math-lora/tokenizer.json
  inflating: phi-4-jee-math-lora/tokenizer_config.json
  inflating: phi-4-jee-math-lora/README.md

In [3]:
!pip install mergekit

Collecting mergekit
  Downloading mergekit-0.1.4-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mergekit) (2.10.0+cu128)
Collecting tqdm==4.67.1 (from mergekit)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 2.6 MB/s eta 0:00:00
Collecting click==8.2.1 (from mergekit)
  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
Collecting safetensors~=0.5.2 (from mergekit)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting accelerate~=1.6.0 (from mergekit)
  Downloading accelerate-1.6.0-py3-none-any.whl.metadata (19 kB)
Collecting pydantic~=2.10.6 (from mergekit)
  Downloading pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
Collecting immutables==0.21 (from mergekit)
  Downloading immutables-0.21-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: transformers>=4.45.2 in /usr/local/lib/python3.12/dist-packages (from mergekit) (5.3.0)
Requirement already satisfied: tokenizers>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from mergekit) (0.22.2)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from mergekit) (1.7.1)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (from mergekit) (0.18.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from mergekit) (4.15.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from mergekit) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from mergekit) (5.29.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from mergekit) (1.16.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from mergekit) (4.3.0)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate~=1.6.0->mergekit) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate~=1.6.0->mergekit) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate~=1.6.0->mergekit) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate~=1.6.0->mergekit) (6.0.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->mergekit) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->mergekit) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->mergekit) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->mergekit) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->mergekit) (0.24.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.10.6->mergekit) (0.7.0)
Collecting pydantic-core==2.27.2 (from pydantic~=2.10.6->mergekit)
  Downloading pydantic_core-2.27.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->mergekit) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->mergekit) (1.4.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.2->mergekit) (2025.11.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->mergekit) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->mergekit) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets->mergekit) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->mergekit) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->mergekit) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->mergekit) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->mergekit) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->mergekit) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->mergekit) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->mergekit) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->mergekit) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->mergekit) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets->mergekit) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->mergekit) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->mergekit) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->mergekit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->mergekit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->mergekit) (2025.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->mergekit) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->mergekit) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub->mergekit) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets->mergekit) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->mergekit) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->mergekit) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub->mergekit) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub->mergekit) (0.1.2)
Downloading mergekit-0.1.4-py3-none-any.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 9.2 MB/s eta 0:00:00
Downloading click-8.2.1-py3-none-any.whl (102 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.2/102.2 kB 5.8 MB/s eta 0:00:00
Downloading immutables-0.21-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.9/104.9 kB 5.9 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 3.2 MB/s eta 0:00:00
Downloading accelerate-1.6.0-py3-none-any.whl (354 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.7/354.7 kB 15.6 MB/s eta 0:00:00
Downloading pydantic-2.10.6-py3-none-any.whl (431 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.7/431.7 kB 20.0 MB/s eta 0:00:00
Downloading pydantic_core-2.27.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 41.9 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 18.6 MB/s eta 0:00:00
Installing collected packages: tqdm, safetensors, pydantic-core, immutables, click, pydantic, accelerate, mergekit
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.7.0
    Uninstalling safetensors-0.7.0:
      Successfully uninstalled safetensors-0.7.0
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.41.4
    Uninstalling pydantic_core-2.41.4:
      Successfully uninstalled pydantic_core-2.41.4
  Attempting uninstall: click
    Found existing installation: click 8.3.1
    Uninstalling click-8.3.1:
      Successfully uninstalled click-8.3.1
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.12.3
    Uninstalling pydantic-2.12.3:
      Successfully uninstalled pydantic-2.12.3
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.13.0
    Uninstalling accelerate-1.13.0:
      Successfully uninstalled accelerate-1.13.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rasterio 1.5.0 requires click!=8.2.*,>=4.0, but you have click 8.2.1 which is incompatible.
mcp 1.26.0 requires pydantic<3.0.0,>=2.11.0, but you have pydantic 2.10.6 which is incompatible.
google-adk 1.27.1 requires pydantic<3.0.0,>=2.12.0, but you have pydantic 2.10.6 which is incompatible.
Successfully installed accelerate-1.6.0 click-8.2.1 immutables-0.21 mergekit-0.1.4 pydantic-2.10.6 pydantic-core-2.27.2 safetensors-0.5.3 tqdm-4.67.1

In [4]:
!pip install llm-blender tyro rich wandb

Collecting llm-blender
  Downloading llm_blender-0.0.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (1.0.11)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (13.9.4)
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.25.1)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from llm-blender) (5.3.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from llm-blender) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llm-blender) (2.0.2)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from llm-blender) (1.6.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from llm-blender) (0.5.3)
Collecting dataclasses-json (from llm-blender)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from llm-blender) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from llm-blender) (5.29.6)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro) (4.5.1)
Requirement already satisfied: typing-extensions>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from tyro) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich) (2.19.2)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from wandb) (8.2.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (3.1.46)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb) (26.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb) (4.9.4)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.10.6)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.54.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (2.27.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2026.2.25)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->llm-blender) (5.9.5)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate->llm-blender) (1.7.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (3.25.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->llm-blender) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->llm-blender) (1.4.3)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llm-blender)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->llm-blender)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->llm-blender) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->llm-blender) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers->llm-blender) (0.24.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers->llm-blender) (4.67.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.0->accelerate->llm-blender) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.0->accelerate->llm-blender) (0.28.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->llm-blender) (1.3.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->llm-blender)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->llm-blender) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers->llm-blender) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers->llm-blender) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21.0->accelerate->llm-blender) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21.0->accelerate->llm-blender) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.21.0->accelerate->llm-blender) (0.16.0)
Downloading llm_blender-0.0.2-py3-none-any.whl (92 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 kB 5.2 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 6.0 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: mypy-extensions, marshmallow, typing-inspect, dataclasses-json, llm-blender
Successfully installed dataclasses-json-0.6.7 llm-blender-0.0.2 marshmallow-3.26.2 mypy-extensions-1.1.0 typing-inspect-0.9.0

In [5]:
!pip install weave

Collecting weave
  Downloading weave-0.52.35-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: cachetools>=6.2.4 in /usr/local/lib/python3.12/dist-packages (from weave) (6.2.6)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from weave) (8.2.1)
Collecting diskcache-weave==5.6.3.post1 (from weave)
  Downloading diskcache_weave-5.6.3.post1-py3-none-any.whl.metadata (20 kB)
Collecting gql>=3.0.0 (from gql[httpx]>=3.0.0->weave)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: jsonschema>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from weave) (4.26.0)
Requirement already satisfied: packaging>=21.0 in /usr/local/lib/python3.12/dist-packages (from weave) (26.0)
Collecting polyfile-weave>=0.5.9 (from weave)
  Downloading polyfile_weave-0.5.9-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from weave) (2.10.6)
Requirement already satisfied: sentry-sdk<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from weave) (2.54.0)
Requirement already satisfied: tenacity!=8.4.0,>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from weave) (9.1.4)
Requirement already satisfied: wandb>=0.17.1 in /usr/local/lib/python3.12/dist-packages (from weave) (0.25.1)
Collecting graphql-core<3.3,>=3.2 (from gql>=3.0.0->gql[httpx]>=3.0.0->weave)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (1.23.0)
Collecting backoff<3.0,>=1.11.1 (from gql>=3.0.0->gql[httpx]>=3.0.0->weave)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: anyio<5,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gql>=3.0.0->gql[httpx]>=3.0.0->weave) (4.12.1)
Requirement already satisfied: httpx<1,>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from gql[httpx]>=3.0.0->weave) (0.28.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.23.0->weave) (0.30.0)
Collecting abnf~=2.2.0 (from polyfile-weave>=0.5.9->weave)
  Downloading abnf-2.2.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: chardet>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (5.2.0)
Collecting cint>=1.0.0 (from polyfile-weave>=0.5.9->weave)
  Downloading cint-1.0.0-py3-none-any.whl.metadata (511 bytes)
Collecting fickling>=0.0.8 (from polyfile-weave>=0.5.9->weave)
  Downloading fickling-0.1.10-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.25.2)
Requirement already satisfied: graphviz>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (0.21)
Collecting intervaltree>=2.4.0 (from polyfile-weave>=0.5.9->weave)
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: jinja2>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.1.6)
Collecting kaitaistruct>=0.11 (from polyfile-weave>=0.5.9->weave)
  Downloading kaitaistruct-0.11-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: networkx>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (3.6.1)
Requirement already satisfied: Pillow>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (11.3.0)
Requirement already satisfied: pyyaml>=3.13 in /usr/local/lib/python3.12/dist-packages (from polyfile-weave>=0.5.9->weave) (6.0.3)
Collecting pdfminer.six>=20251230 (from polyfile-weave>=0.5.9->weave)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->weave) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->weave) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->weave) (4.15.0)
Requirement already satisfied: urllib3>=1.26.11 in /usr/local/lib/python3.12/dist-packages (from sentry-sdk<3.0.0,>=2.0.0->weave) (2.5.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from sentry-sdk<3.0.0,>=2.0.0->weave) (2026.2.25)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb>=0.17.1->weave) (3.1.46)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb>=0.17.1->weave) (4.9.4)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<7,>4.21.0 in /usr/local/lib/python3.12/dist-packages (from wandb>=0.17.1->weave) (5.29.6)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb>=0.17.1->weave) (2.32.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.0->gql>=3.0.0->gql[httpx]>=3.0.0->weave) (3.11)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb>=0.17.1->weave) (4.0.12)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.27.0->gql[httpx]>=3.0.0->weave) (0.16.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from intervaltree>=2.4.0->polyfile-weave>=0.5.9->weave) (2.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.1.0->polyfile-weave>=0.5.9->weave) (3.0.3)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (3.4.6)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (43.0.3)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql>=3.0.0->gql[httpx]>=3.0.0->weave) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql>=3.0.0->gql[httpx]>=3.0.0->weave) (0.4.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (2.0.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb>=0.17.1->weave) (5.0.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20251230->polyfile-weave>=0.5.9->weave) (3.0)
Downloading weave-0.52.35-py3-none-any.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 955.0/955.0 kB 22.3 MB/s eta 0:00:00
Downloading diskcache_weave-5.6.3.post1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/45.9 kB 6.2 MB/s eta 0:00:00
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 13.0 MB/s eta 0:00:00
Downloading polyfile_weave-0.5.9-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 76.9 MB/s eta 0:00:00
Downloading abnf-2.2.0-py3-none-any.whl (39 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading cint-1.0.0-py3-none-any.whl (5.6 kB)
Downloading fickling-0.1.10-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.9/52.9 kB 6.7 MB/s eta 0:00:00
Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 26.5 MB/s eta 0:00:00
Downloading intervaltree-3.2.1-py2.py3-none-any.whl (25 kB)
Downloading kaitaistruct-0.11-py2.py3-none-any.whl (11 kB)
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 124.9 MB/s eta 0:00:00
Installing collected packages: kaitaistruct, intervaltree, graphql-core, fickling, diskcache-weave, cint, backoff, abnf, gql, pdfminer.six, polyfile-weave, weave
Successfully installed abnf-2.2.0 backoff-2.2.1 cint-1.0.0 diskcache-weave-5.6.3.post1 fickling-0.1.10 gql-4.0.0 graphql-core-3.2.8 intervaltree-3.2.1 kaitaistruct-0.11 pdfminer.six-20260107 polyfile-weave-0.5.9 weave-0.52.35

In [7]:
!pip install sympy pandas

Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy) (1.3.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
import os
import unsloth
import transformers.utils.hub

from sympy import sympify, simplify
# Bypass cache bug
transformers.utils.hub.TRANSFORMERS_CACHE = os.getenv("HF_HOME", "~/.cache/huggingface/hub")

# MUST be first
from unsloth import FastLanguageModel, PatchFastRL
PatchFastRL("GRPO", FastLanguageModel)

import torch
import re
from datasets import load_dataset
from trl import GRPOTrainer, GRPOConfig

# 1. Load model
max_seq_length = 4096
print("Loading your SFT adapter weights...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="phi-4-jee-math-lora",
    max_seq_length=max_seq_length,
    load_in_4bit=True,
)

# ---------------- REWARD FUNCTIONS ---------------- #

def clean_math(expr):
    expr = str(expr)

    expr = expr.replace("$", "")
    expr = expr.replace("\\boxed{", "").replace("}", "")
    expr = expr.replace("\\frac", "")
    expr = expr.replace("\\over", "/")

    expr = expr.replace("{", "").replace("}", "")
    expr = expr.strip()

    return expr


def symbolic_equal(a, b):
    try:
        a_expr = sympify(clean_math(a))
        b_expr = sympify(clean_math(b))
        return simplify(a_expr - b_expr) == 0
    except:
        return False


# ================== REWARD FUNCTIONS ==================

def format_reward_func(completions, **kwargs):
    rewards = []
    for output in completions:
        if "<think>" in output and "</think>" in output and "\\boxed{" in output:
            rewards.append(0.4)
        else:
            rewards.append(0.0)
    return rewards


def completion_reward_func(completions, **kwargs):
    rewards = []
    for output in completions:
        if re.search(r"\\boxed\{.*?\}\s*$", output.strip()):
            rewards.append(0.2)
        else:
            rewards.append(0.0)
    return rewards


def accuracy_reward_func(completions, answer=None, prompts=None, **kwargs):
    rewards = []

    for i in range(len(completions)):
        output = completions[i]
        ground_truth = answer[i] if answer is not None else None

        match = re.search(r"\\boxed\{(.*?)\}", output)

        if match and ground_truth is not None:
            generated = match.group(1)

            if symbolic_equal(generated, ground_truth):
                rewards.append(3.0)
                continue

            try:
                if abs(float(eval(clean_math(generated))) - float(eval(clean_math(ground_truth)))) < 1e-6:
                    rewards.append(3.0)
                    continue
            except:
                pass

            rewards.append(0.15)

        else:
            rewards.append(0.1)

    return rewards

# ---------------- DATA ---------------- #

dataset = load_dataset("json", data_files="train_rl_colab.jsonl", split="train")

def enforce_chat_format(example):
    clean_prompt = re.sub(r"<.*?>", "", example["prompt"])

    formatted_user_prompt = f"""
Solve the following math problem.

Respond EXACTLY in this format:
<think>
step-by-step reasoning
</think>
\\boxed{{final answer}}

Question:
{clean_prompt}
"""

    return {
        "prompt": tokenizer.apply_chat_template(
            [{"role": "user", "content": formatted_user_prompt}],
            tokenize=False,
            add_generation_prompt=True,
        ),
        "answer": example["answer"],
    }

dataset = dataset.map(enforce_chat_format)

# ---------------- TRAINING ---------------- #

training_args = GRPOConfig(
    output_dir="grpo_outputs",
    learning_rate=5e-6,
    num_train_epochs=1,

    per_device_train_batch_size=6,
    gradient_accumulation_steps=3,

    num_generations=3,

    max_completion_length=400,

    max_prompt_length=768,
    logging_steps=5,
    optim="adamw_8bit",
    report_to="none",
)

trainer = GRPOTrainer(
    model=model,
    reward_funcs=[
        format_reward_func,
        accuracy_reward_func,
        completion_reward_func,
    ],
    args=training_args,
    train_dataset=dataset,
)

print("Starting GRPO Training...")
trainer.train()

# ---------------- SAVE ---------------- #

print("Saving RL-optimized model...")
model.save_pretrained("phi-4-jee-math-grpo")
tokenizer.save_pretrained("phi-4-jee-math-grpo")
print("Done!")

Unsloth: UnslothBCOTrainer is already patched.
Unsloth: UnslothCPOTrainer is already patched.
Unsloth: UnslothDPOTrainer is already patched.
Unsloth: UnslothGKDTrainer is already patched.
Unsloth: UnslothGRPOTrainer is already patched.
Unsloth: UnslothKTOTrainer is already patched.
Unsloth: UnslothNashMDTrainer is already patched.
Unsloth: UnslothOnlineDPOTrainer is already patched.
Unsloth: UnslothORPOTrainer is already patched.
Unsloth: UnslothPPOTrainer is already patched.
Unsloth: UnslothPRMTrainer is already patched.
Unsloth: UnslothRewardTrainer is already patched.
Unsloth: UnslothRLOOTrainer is already patched.
Unsloth: UnslothSFTTrainer is already patched.
Unsloth: UnslothXPOTrainer is already patched.
Loading your SFT adapter weights...
==((====))==  Unsloth 2026.3.15: Fast Phi3 patching. Transformers: 5.3.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/194 [00:00<?, ?it/s]

Starting GRPO Training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 200 | Num Epochs = 1 | Total steps = 33
O^O/ \_/ \    Batch size per device = 6 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (6 x 3 x 1) = 18
 "-____-"     Trainable parameters = 8,912,896 of 3,844,934,656 (0.23% trained)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=400) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Saving RL-optimized model...
Done!

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
!cp -r /content/phi-4-jee-math-grpo /content/drive/MyDrive/phi-4-jee-math-grpo-final

print("Transfer complete! Check your Google Drive.")

Transfer complete! Check your Google Drive.

In [14]:
import pandas as pd
df_t = pd.read_csv('/content/jee_data_all.csv')
df_m = df_t[df_t['subject'] == 'maths']

In [16]:
import pandas as pd

print("Preparing the 50-question benchmark dataset...")

# 1. Grab the 50 random rows first
sampled_df = df_m.sample(n=50, random_state=42)

# 2. Extract ONLY the two columns we care about into a fresh DataFrame
# This completely destroys any duplicate column errors
clean_test_df = pd.DataFrame({
    "prompt": sampled_df["question"].tolist(),
    "answer": sampled_df["solution"].tolist()
})

# 3. Save it to the exact filename
file_name = "test_50_colab.jsonl"
clean_test_df.to_json(file_name, orient="records", lines=True)

print(f"SUCCESS: Saved 50 clean questions to '{file_name}'.")
print("You are clear to run the benchmark script now!")

Preparing the 50-question benchmark dataset...
SUCCESS: Saved 50 clean questions to 'test_50_colab.jsonl'.
You are clear to run the benchmark script now!

In [ ]:
# Convert your new GRPO model to a 4-bit GGUF file
model.save_pretrained_gguf(
    "phi-4-jee-math-grpo-gguf",
    tokenizer,
    quantization_method = "q4_k_m"
)

In [ ]:
# This uses a wildcard (*.gguf) to grab the exact file Unsloth just created
# and drops it directly into the main folder of your Google Drive.
!cp *.gguf /content/drive/MyDrive/

print("GGUF successfully backed up to Google Drive!")

In [ ]:
import pandas as pd
import torch
import re
import json
from tqdm import tqdm
from unsloth import FastLanguageModel
from sympy import sympify, simplify # Added the missing imports from your logic

# ==========================================
# 1. CONFIGURATION
# ==========================================
# Run this script twice:
# First time -> MODEL_PATH = "phi-4-jee-math-lora" (Outputs SFT results)
# Second time -> MODEL_PATH = "phi-4-jee-math-grpo" (Outputs GRPO results)
MODEL_PATH = "phi-4-jee-math-grpo"
OUTPUT_CSV_NAME = f"benchmark_results_{MODEL_PATH.split('-')[-1]}.csv"
TEST_DATA_FILE = "test_50_colab.jsonl"

# ==========================================
# 2. LOAD MODEL & TOKENIZER
# ==========================================
print(f"Loading model: {MODEL_PATH} for inference...")
max_seq_length = 4096
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_PATH,
    max_seq_length = max_seq_length,
    load_in_4bit = True,
)
FastLanguageModel.for_inference(model) # 2x faster inference mode

# ==========================================
# 3. YOUR EXACT EVALUATION LOGIC
# ==========================================
def clean_math(expr):
    if expr is None: return ""
    expr = str(expr)
    expr = expr.replace("$", "").replace("\\boxed{", "").replace("}", "")
    expr = expr.replace("\\frac", "").replace("\\over", "/")
    expr = expr.replace("{", "").replace("}", "").strip()
    return expr

def symbolic_equal(a, b):
    if not a or not b: return False
    try:
        a_expr = sympify(clean_math(a))
        b_expr = sympify(clean_math(b))
        return simplify(a_expr - b_expr) == 0
    except:
        return False

def check_math_accuracy(generated, ground_truth):
    """Replicates the accuracy_reward_func logic."""
    if symbolic_equal(generated, ground_truth):
        return True
    try:
        if abs(float(eval(clean_math(generated))) - float(eval(clean_math(ground_truth)))) < 1e-6:
            return True
    except:
        pass
    return False

# ==========================================
# 4. DATA LOADING & PROMPT FORMATTING
# ==========================================
print(f"Loading test questions from {TEST_DATA_FILE}...")
test_df = pd.read_json(TEST_DATA_FILE, lines=True)

def format_test_prompt(question_text):
    """Exactly matches the enforce_chat_format function from your training."""
    clean_prompt = re.sub(r"<.*?>", "", question_text)
    formatted_user_prompt = f"""
Solve the following math problem.

Respond EXACTLY in this format:
<think>
step-by-step reasoning
</think>
\\boxed{{final answer}}

Question:
{clean_prompt}
"""
    return tokenizer.apply_chat_template(
        [{"role": "user", "content": formatted_user_prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )

# ==========================================
# 5. THE INFERENCE LOOP
# ==========================================
results = []
correct_math_count = 0
correct_format_count = 0

print(f"Starting evaluation on {len(test_df)} questions...")

for index, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Benchmarking"):
    prompt = format_test_prompt(row['prompt'])
    ground_truth = str(row['answer']).strip()

    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")

    # Generate the response (Matching max_completion_length from training)
    outputs = model.generate(
        **inputs,
        max_new_tokens = 450,
        temperature = 0.1,
        use_cache = True,
        pad_token_id = tokenizer.eos_token_id
    )

    # Decode only the generated response
    generated_text = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)

    # 1. Check Formatting
    has_think = "<think>" in generated_text and "</think>" in generated_text
    match = re.search(r"\\boxed\{(.*?)\}", generated_text)
    extracted_ans = match.group(1).strip() if match else None

    is_format_correct = has_think and (extracted_ans is not None)

    # 2. Check Math Accuracy
    is_math_correct = check_math_accuracy(extracted_ans, ground_truth)

    if is_format_correct: correct_format_count += 1
    if is_math_correct: correct_math_count += 1

    results.append({
        "Question": row['prompt'],
        "Ground_Truth": ground_truth,
        "Model_Answer": extracted_ans,
        "Format_Correct": is_format_correct,
        "Math_Correct": is_math_correct,
        "Full_Generation": generated_text
    })

# ==========================================
# 6. SAVE AND REPORT
# ==========================================
results_df = pd.DataFrame(results)
results_df.to_csv(OUTPUT_CSV_NAME, index=False)

accuracy = (correct_math_count / len(test_df)) * 100
format_rate = (correct_format_count / len(test_df)) * 100

print("\n" + "="*50)
print(f"BENCHMARK REPORT: {MODEL_PATH}")
print("="*50)
print(f"Total Questions Evaluated: {len(test_df)}")
print(f"Formatting Success Rate:   {format_rate:.2f}%")
print(f"Mathematical Accuracy:     {accuracy:.2f}%")
print("="*50)
print(f"Detailed logs saved to: {OUTPUT_CSV_NAME}")

Loading model: phi-4-jee-math-grpo for inference...
==((====))==  Unsloth 2026.3.15: Fast Phi3 patching. Transformers: 5.3.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/194 [00:00<?, ?it/s]

Loading test questions from test_50_colab.jsonl...
Starting evaluation on 50 questions...

Benchmarking:   0%|          | 0/50 [00:00<?, ?it/s]Both `max_new_tokens` (=450) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
import pandas as pd
import torch
import re
import json
from tqdm import tqdm
from unsloth import FastLanguageModel
from sympy import sympify, simplify # Added the missing imports from your logic

# ==========================================
# 1. CONFIGURATION
# ==========================================
# Run this script twice:
# First time -> MODEL_PATH = "phi-4-jee-math-lora" (Outputs SFT results)
# Second time -> MODEL_PATH = "phi-4-jee-math-grpo" (Outputs GRPO results)
MODEL_PATH = "phi-4-jee-math-lora"
OUTPUT_CSV_NAME = f"benchmark_results_{MODEL_PATH.split('-')[-1]}.csv"
TEST_DATA_FILE = "test_50_colab.jsonl"

# ==========================================
# 2. LOAD MODEL & TOKENIZER
# ==========================================
print(f"Loading model: {MODEL_PATH} for inference...")
max_seq_length = 4096
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_PATH,
    max_seq_length = max_seq_length,
    load_in_4bit = True,
)
FastLanguageModel.for_inference(model) # 2x faster inference mode

# ==========================================
# 3. YOUR EXACT EVALUATION LOGIC
# ==========================================
def clean_math(expr):
    if expr is None: return ""
    expr = str(expr)
    expr = expr.replace("$", "").replace("\\boxed{", "").replace("}", "")
    expr = expr.replace("\\frac", "").replace("\\over", "/")
    expr = expr.replace("{", "").replace("}", "").strip()
    return expr

def symbolic_equal(a, b):
    if not a or not b: return False
    try:
        a_expr = sympify(clean_math(a))
        b_expr = sympify(clean_math(b))
        return simplify(a_expr - b_expr) == 0
    except:
        return False

def check_math_accuracy(generated, ground_truth):
    """Replicates the accuracy_reward_func logic."""
    if symbolic_equal(generated, ground_truth):
        return True
    try:
        if abs(float(eval(clean_math(generated))) - float(eval(clean_math(ground_truth)))) < 1e-6:
            return True
    except:
        pass
    return False

# ==========================================
# 4. DATA LOADING & PROMPT FORMATTING
# ==========================================
print(f"Loading test questions from {TEST_DATA_FILE}...")
test_df = pd.read_json(TEST_DATA_FILE, lines=True)

def format_test_prompt(question_text):
    """Exactly matches the enforce_chat_format function from your training."""
    clean_prompt = re.sub(r"<.*?>", "", question_text)
    formatted_user_prompt = f"""
Solve the following math problem.

Respond EXACTLY in this format:
<think>
step-by-step reasoning
</think>
\\boxed{{final answer}}

Question:
{clean_prompt}
"""
    return tokenizer.apply_chat_template(
        [{"role": "user", "content": formatted_user_prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )

# ==========================================
# 5. THE INFERENCE LOOP
# ==========================================
results = []
correct_math_count = 0
correct_format_count = 0

print(f"Starting evaluation on {len(test_df)} questions...")

for index, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Benchmarking"):
    prompt = format_test_prompt(row['prompt'])
    ground_truth = str(row['answer']).strip()

    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")

    # Generate the response (Matching max_completion_length from training)
    outputs = model.generate(
        **inputs,
        max_new_tokens = 450,
        temperature = 0.1,
        use_cache = True,
        pad_token_id = tokenizer.eos_token_id
    )

    # Decode only the generated response
    generated_text = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)

    # 1. Check Formatting
    has_think = "<think>" in generated_text and "</think>" in generated_text
    match = re.search(r"\\boxed\{(.*?)\}", generated_text)
    extracted_ans = match.group(1).strip() if match else None

    is_format_correct = has_think and (extracted_ans is not None)

    # 2. Check Math Accuracy
    is_math_correct = check_math_accuracy(extracted_ans, ground_truth)

    if is_format_correct: correct_format_count += 1
    if is_math_correct: correct_math_count += 1

    results.append({
        "Question": row['prompt'],
        "Ground_Truth": ground_truth,
        "Model_Answer": extracted_ans,
        "Format_Correct": is_format_correct,
        "Math_Correct": is_math_correct,
        "Full_Generation": generated_text
    })

# ==========================================
# 6. SAVE AND REPORT
# ==========================================
results_df = pd.DataFrame(results)
results_df.to_csv(OUTPUT_CSV_NAME, index=False)

accuracy = (correct_math_count / len(test_df)) * 100
format_rate = (correct_format_count / len(test_df)) * 100

print("\n" + "="*50)
print(f"BENCHMARK REPORT: {MODEL_PATH}")
print("="*50)
print(f"Total Questions Evaluated: {len(test_df)}")
print(f"Formatting Success Rate:   {format_rate:.2f}%")
print(f"Mathematical Accuracy:     {accuracy:.2f}%")
print("="*50)
print(f"Detailed logs saved to: {OUTPUT_CSV_NAME}")